# cSpell:disable
# NOTE: manage fish abbreviations
# https://fishshell.com/docs/current/cmds/abbr.html

abbr ai "gemini -p"
abbr ast "aw set -t (aw list | fzf-tmux -p --reverse --preview 'aw set -t {}')"

abbr bi "brew install"
abbr bic "brew install --cask"
abbr bin "brew info"
abbr binc "brew info --cask"
abbr bl "brew leaves"
abbr blr "brew leaves --installed-on-request"
abbr blp "brew leaves --installed-as-dependency"
abbr bs "brew search"
abbr bu "brew update"
abbr buu "brew upgrade"
abbr bui "brew uninstall"
abbr bnv "bun create vite MYAPP --template"
abbr bna "bunx create-astro@latest MYAPP"

abbr c clear
abbr cat bat
abbr cx "chmod +x"

abbr dc "docker compose"
abbr dcd "docker compose down"
abbr dcdv "docker compose down -v"
abbr dcr "docker compose restart"
abbr dcud "docker compose up -d"
abbr dps "docker ps --format 'table {{.Names}}\t{{.Status}}'"

abbr e exit
abbr ee "espanso edit"
abbr er "espanso restart"
abbr escli "docker run -p 5000:5000 elastichq/elasticsearch-hq"

abbr fi "fisher install"
abbr fr "fisher refresh"
abbr fu "fisher update"
abbr fl "fisher list | sed 's/.*/"&"/'"

abbr gad "git add ."
abbr gbh "git branch -v"
abbr gct "git commit"
abbr gca "git commit -av"
abbr gcl "git clone"
abbr gco "git checkout -b"
abbr gdf "nvim +DiffviewOpen"
abbr gfh "git fetch --all"
abbr gma "git merge --abort"
abbr gmc "git merge --continue"
abbr gols "go list -m -json"
abbr gpl "git pull"
abbr gph "git push"
abbr gpom "git pull origin main"
abbr gpr "gh pr create"
abbr gpum "git pull upstream master"
abbr gr "git remote"
abbr gra "git remote add"
abbr grao "git remote add origin"
abbr grau "git remote add upstream"
abbr grv "git remote -v"
abbr gsb "git stash branch"
abbr gsd "git stash drop"
abbr gsh "git stash"
abbr gsl "git stash list"
abbr gsp "git stash pop"
abbr gss "git status"
abbr gsw "git switch"
abbr gsz "git ls-files -z | xargs -0 du -ch | tail -n1"

abbr hd "history delete --exact --case-sensitive \'(history | fzf-tmux -p -m)\'"

abbr k "kubectl"
abbr kaf "kubectl apply -f"
abbr kai "kubectl ai --model gemini-2.5-pro-exp-03-25 --quiet"
abbr kall "killall"
abbr kc "kubectx"
abbr kdl "kubectl delete"
abbr kds "kubectl describe"
abbr kk "yozf"
abbr kns "kubens"
abbr kg "kubectl get"
abbr kgp "kubectl get pods"
abbr kgpa "kubectl get pods -A"
abbr kgs "kubectl get services"
abbr kgsa "kubectl get services -A"

abbr ls "eza"
abbr ll "eza -al"
abbr lt "eza -T"
abbr ldk "lazydocker"
abbr lg "lazygit"
abbr lsh "lazyssh"

abbr mcpcli "DANGEROUSLY_OMIT_AUTH=true npx @modelcontextprotocol/inspector"

abbr nb "npm run build"
abbr nd "npm run dev"
abbr nf "fastfetch"
abbr ni "npm install"
abbr nt "npm run test"
abbr nxdg "nx dep-graph"

abbr p "pnpm run (jq -r '.scripts|to_entries[]|((.key))' package.json | fzf-tmux -p --border-label='pnpm run')"
abbr pa "pnpm add"
abbr pb "pnpm build"
abbr pd "pnpm dev"
abbr pe "pnpm e2e"
abbr pg "pnpm generate"
abbr ph "pnpm help"
abbr pi "pnpm install"
abbr pim "pnpm import"
abbr pir "pnpm rebuild"
abbr pit "pnpm install-test"
abbr pl "pnpm link"
abbr pls "pnpm ls"
abbr pr "pnpm run"
abbr psa "pnpm store add"
abbr psp "pnpm store prune"
abbr pss "pnpm store status"
abbr pst "pnpm start"
abbr pt "pnpm test"
abbr pu "pnpm update"
abbr pul "pnpm unlink"
abbr pw "pnpm web"
abbr pwdc "pwd | pbcopy"

abbr rmr "rm -rf"

abbr sa "SwitchAudioSource -t output -s (SwitchAudioSource -t output -a | fzf-tmux -p --reverse)"
abbr sai "SwitchAudioSource -t input -s (SwitchAudioSource -t input -a | fzf-tmux -p --reverse)"
abbr sao "SwitchAudioSource -t output -s (SwitchAudioSource -t output -a | fzf-tmux -p --reverse)"
abbr sf "source ~/.config/fish/config.fish && source ~/.config/fish/conf.d/*.fish"
abbr st "tmux source ~/.config/tmux/tmux.conf"
abbr convsingbox "docker run -d -p 8082:8080 ghcr.io/xmdhs/clash2sfa"

abbr t "tmux"
abbr ta "tmux a"
abbr tat "tmux attach -t"
abbr tk "tmux kill-server"
abbr tks "tmux kill-server"
abbr top htop
abbr tr "tldr --list | fzf --header 'tldr (tealdeer)' --reverse --preview 'tldr {1} --color=always' --preview-window=right,80% | xargs tldr"
abbr tn "tmux new -s (basename (pwd))"


abbr vi "nvim"
abbr vfzf "nvim (fd --type f --hidden --follow --exclude .git | fzf-tmux -p -w 100 --reverse --preview 'bat --color=always --style=numbers --line-range=:500 {}')"
abbr va "nvim ~/.config/alacritty/alacritty.toml"
abbr vf "nvim ~/.config/fish/config.fish"
abbr vg "nvim ~/.config/ghostty/config"
abbr vp "nvim package.json"
abbr vt "nvim ~/.config/tmux/tmux.conf"
abbr vv "nvim ~/.config/nvim/lua/plugins"

abbr xi   "sudo xbps-install"
abbr xq   "sudo xbps-query"
abbr xrm  "sudo xbps-remove"
abbr xrc  "sudo xbps-reconfigure"
abbr xri  "sudo xbps-rindex"
abbr xalt "sudo xbps-alternatives"
abbr xp   "sudo xbps-pkgdb"
abbr xm   "sudo xmirror"

abbr y yarn
abbr ya "yarn add"
abbr yad "yarn add -D"
abbr yb "yarn build"
abbr yd "yarn dev"
abbr ye "yarn e2e"
abbr yg "yarn generate"
abbr yi "yarn install --frozen-lockfile"
abbr yl "yarn lint"
abbr yp "yarn plop"
abbr ypm "yarn plop model"
abbr ys "yarn server"
abbr yt "yarn test"
abbr yu "yarn ui"
abbr yw "yarn web"

abbr za "zoxide add"
abbr ze "zoxide edit"

abbr :GoToCommand fzf-history-widget
abbr :GoToFile "nvim +GoToFile"
abbr :bd exit
abbr :q "tmux kill-server"
